site_name: RailroadDES


theme:
  material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css

extra_javascript:
  - optionalConfig.js
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
  - extra-loader.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

#plugins:
##  - search
#  - mkdocstrings:
##      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
#      default_handler: python
#      handlers:
#        python:
#          options:
#            show_source: false